languageCode = "en-us"
theme = "conference"
title = "Devops Gathering 2017"
baseurl = "https://devops-gathering.io"
enableRobotsTXT = true
[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Devops Gathering 2017"
	description = "The DevOps Gathering is an international community conference located in Germany. | March 23 - 25, 2017 | All about Docker, Kubernetes, Microservices, Clouds and everything else regarding DevOps."
	keywords = "DevOps Conference, DevOps Gathering, DevOps Community, DevOps Training, DevOps Workshop, Docker, DevOps, Docker Conference, Microservices, Kubernetes, Clouds"
	# The path must be relative to the static folder
	favicon = "favicon.ico"

	[params.meta]
	 image = "meta-image.png"

	# About Devops Gathering
	[params.about]
		title="About DevOps Gathering"

	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "DevOps Gathering 2017"
		subtitle   = "Take your seat and get pushed to the next level"
		date = "23 â€“ 25 March, 2017"
    subtitle2 = "bee42 solutions proudly presents"
		location = "G Data Campus Bochum"
		buttonText = "Call for Papers"
		link = "https://papercall.io/devops-gathering2017"

	# Comitee section
	[[params.commitee.members]]
		img = "peter-rossbach-bee42.png"
		name = "Peter Rossbach"
		firm = "bee42 solutions gmbh"
		bio = "Peter Rossbach is a infra coder, system architect and coach of numerous web systems and founder of the bee42 solutions gmbh. He is also CTO of Setlog Gmbh a Supply Chain Management company. Peter realized appropriate infrastructure products and offer many training based on the Docker and Kubernetes ecosystem, current web technologies, microservices, Apache Tomcat, Java, NoSQL databases and cloud platforms."

	[[params.commitee.members]]
		img = "dieter-reuter.png"
		name = "Dieter Reuter"
		firm = "bee42 solutions gmbh"
		bio  = "Dieter Reuter is a Senior Consultant at bee42 solutions gmbh and Docker Captain at Hypriot with more than 30 years of enterprise IT experience and unquenchable curiosity. Dealing with cutting-edge cloud technologies, obsessed with the DevOps movement and its associated automation. Dieter is using Docker from the early days on and is pushing Docker and Containers to ARM based IoT devices with rocket-like speed."

	# Contact section
	[params.contact]
		headline = "Questions?"
		description = "Send us an email and we will get back to you as soon as possible!"
		email = "info@devops-gathering.io"
		twitter ="https://twitter.com/devopsgathering"

    [params.tickets]
         enabled = true

	[params.talks]
		lunchbreak="13:00-14:00"
		text="These Talks are a perfect fit for DevOps Engineers.<br> Attendees obtain interesseting stories from Experts with different knowledge areas.<br> The complete list of talks and the timeline we publish very soon!"


	[params.workshops]
		lunchbreak="12:30-13:30"
		text="This Docker Workshops are an perfect fit for DevOps Engineers.<br> Attendees have the chance to learn from some exciting Docker Captains and Experts. <br> The concept of the workshop is to leave room for experiments.<br>  The goal of the workshops are to interact with one another and learn from the speaker a lot."
